// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heiemzbmkdtzipuqqmro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlaWVtemJta2R0emlwdXFxbXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDE1NjksImV4cCI6MjA2NTcxNzU2OX0.uj3v4MTz93r_hcy6_YSAuQzEPBdkup2w-09y23pPpKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);