
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// These are public keys that are safe to expose in frontend
const SUPABASE_URL = "https://heiemzbmkdtzipuqqmro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlaWVtemJta2R0emlwdXFxbXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDE1NjksImV4cCI6MjA2NTcxNzU2OX0.uj3v4MTz93r_hcy6_YSAuQzEPBdkup2w-09y23pPpKo";

// Note: The above keys are PUBLIC and safe to expose in frontend code.
// Private keys like GEMINI_API_KEY are stored securely in Supabase Edge Function environment
// and are never exposed to the client-side code.

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
